export const REQUEST_CART_ITEM_TO_SPRING = 'REQUEST_CART_ITEM_TO_SPRING'
export const REQUEST_CART_ITEM_LIST_TO_SPRING = 'REQUEST_CART_ITEM_LIST_TO_SPRING'

export const RESPONSE_MY_REQUEST = "RESPONSE_MY_REQUEST"