export const REQUEST_CART_ITEM_TO_SPRING = 'REQUEST_CART_ITEM_TO_SPRING'
export const REQUEST_CART_ITEM_LIST_TO_SPRING = 'REQUEST_CART_ITEM_LIST_TO_SPRING'

export const RESPONSE_COUNT_REQUEST = "RESPONSE_COUNT_REQUEST"
export const REQUEST_MY_PAGE_DELIVERY_LIST_TO_SPRING = "REQUEST_MY_PAGE_DELIVERY_LIST_TO_SPRING"