
export const SET_COMMON_SURVEY_RESULT = 'SET_COMMON_SURVEY_RESULT';
export const SET_VISCERA_SURVEY_RESULT = 'SET_VISCERA_SURVEY_RESULT';
export const SET_LIFE_SURVEY_RESULT = 'SET_LIFE_SURVEY_RESULT';
